services:
  # Service pour le frontend Vite/React
  frontend:
    build: ./front
    ports:
      - "5173:5173"
    environment:
      - VITE_API_AUTHENTICATION=http://localhost:8000 # Service authentification
      - REACT_APP_SERVICE2_URL=http://service2:8001 # Service 2
    depends_on: # Le front ne démarre pas tant que l'api-authentication n'a pas démarré
      - api-authentication
    volumes: # Conservation du code et des modules dans le conteneur
      - ./front:/app
      - /app/node_modules
    restart: unless-stopped

  # Service api-authentication (FastAPI + Poetry)
  api-authentication:
    build: ./back/api-authentication
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    depends_on: # Le service ne démarre pas tant que la db n'a pas été initialisée
      - db
    volumes: # Conservation du code dans le conteneur
      - ./back/api-authentication:/app
    restart: unless-stopped

  # Service pour la base de données PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=localdb
    ports:
      - "5000:5000"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
# Volume pour persister les données de PostgreSQL
volumes:
  postgres_data:
