version: "3.8"

services:
  # Service pour le frontend Vite/React
  frontend:
    build: ./front
    ports:
      - "3000:80"
    depends_on:
      - api-name-origin-probabilities
      # - service2
    environment:
      - VITE_API_URL=http://localhost:8000
      # - REACT_APP_SERVICE2_URL=http://service2:8001
    restart: unless-stopped

  # Service api-name-origin-probabilities (FastAPI + Poetry)
  api-name-origin-probabilities:
    build: ./back/api-name-origin-probabilities
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5000/localdb
    depends_on:
      - db
    volumes:
      - ./back/api-name-origin-probabilities:/app
    restart: unless-stopped

  # Service backend 2 (FastAPI + Poetry)
  # service2:
  #   build: ./mon-app-backend/service2
  #   ports:
  #     - "8001:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://user:password@db:5432/mon_app_db
  #   depends_on:
  #     - db
  #   restart: unless-stopped

  # Service pour la base de données PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=localdb
    ports:
      - "5000:5000"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
# Volume pour persister les données de PostgreSQL
volumes:
  postgres_data:
